version: '3'

tasks:
  build:
    cmds:
      - |
        docker run --rm --init -it \
        --user $(id -u):$(id -g) \
        --volume $(pwd):/build \
        --volume "${COMPOSER_HOME:-$HOME/.composer}:/composer" \
        composer/satis build satis.json dist
